name: Ethereum Hive

description: Run Ethereum Hive tests with a given client and simulator

inputs:
  # Test configuration
  simulator:
    description: 'Simulator to run (e.g. ethereum/sync)'
    required: true
    type: string
    default: 'ethereum/sync'
  client:
    description: 'Client to test'
    required: true
    type: string
    default: 'go-ethereum'
  client_config:
    description: 'Client configuration in YAML format'
    required: false
    type: string
  extra_flags:
    description: 'Additional flags for hive'
    required: false
    type: string
  # Hive configuration
  hive_repository:
    description: 'Hive repository to use'
    required: false
    type: string
    default: 'ethereum/hive'
  hive_version:
    description: 'Hive version/branch to use'
    required: false
    type: string
    default: 'master'
  go_version:
    description: 'Go version used to build hive'
    required: false
    type: string
    default: '1.21'
  ## S3 upload using rclone
  s3_upload:
    description: 'Upload test results to S3'
    required: false
    default: 'false'
  s3_bucket:
    description: 'S3 bucket name'
    required: false
    type: string
  s3_path:
    description: 'Path prefix in S3 bucket'
    required: false
    type: string
    default: 'hive-results'
  rclone_version:
    description: 'Rclone version to use'
    required: false
    type: string
    default: 'latest'
  rclone_config:
    description: 'Rclone config file'
    required: false
    type: string
    default: '' # Should be base64 encoded. Example: base64 -w 0 rclone.conf
  # Workflow artifact upload
  workflow_artifact_upload:
    description: 'Upload test results as an workflow artifact'
    required: false
    default: 'false'
  workflow_artifact_name:
    description: 'Name of the workflow artifact. If not provided, the name will be the simulator and client name.'
    required: false
    type: string
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go_version }}

    - name: Checkout hive
      uses: actions/checkout@v4
      with:
        repository: ethereum/hive
        ref: ${{ inputs.hive_version }}
        path: ./src

    - name: Build hive
      working-directory: ./src
      shell: bash
      run: |
        go build -o hive .
        go build -o hiveview ./cmd/hiveview

    - name: Create results directory
      shell: bash
      run: mkdir -p /results

    - name: Setup client config
      if: inputs.client_config != ''
      working-directory: ./src
      shell: bash
      run: |
        echo "${{ inputs.client_config }}" > client-config.yaml
        echo "CLIENT_CONFIG_FLAG=--client-file=client-config.yaml" >> $GITHUB_ENV

    - name: Run hive tests
      working-directory: ./src
      shell: bash
      run: |
        set -x
        (./hive \
          --sim "${{ inputs.simulator }}" \
          --client "${{ inputs.client }}" \
          --results-root /results \
          ${CLIENT_CONFIG_FLAG:-} \
          ${{ inputs.extra_flags }} \
           2>&1 || true ) | tee hive.log

        # Check the last 10 lines of the log for the success message
        if tail -n 10 hive.log | grep -q "simulation .* finished"; then
          echo "RUN_SUCCESS=true" >> $GITHUB_ENV
          exit 0
        else
          echo "RUN_SUCCESS=false" >> $GITHUB_ENV
          exit 1
        fi

    - name: Set artifact name
      if: ${{ inputs.workflow_artifact_upload == 'true' && env.RUN_SUCCESS == 'true' }}
      shell: bash
      run: |
        if [ -n "${{ inputs.workflow_artifact_name }}" ]; then
          echo "WORKFLOW_ARTIFACT_NAME=${{ inputs.workflow_artifact_name }}" >> $GITHUB_ENV
        else
          SIMULATOR_NAME=${{ inputs.simulator }}
          # replace / in simulator name with -
          SIMULATOR_NAME=${{ SIMULATOR_NAME//\//- }}
          CLIENT_NAME=${{ inputs.client }}
          echo "WORKFLOW_ARTIFACT_NAME=$SIMULATOR_NAME-$CLIENT_NAME" >> $GITHUB_ENV
        fi

    - name: Upload test results as workflow artifact
      if: ${{ inputs.workflow_artifact_upload == 'true' && env.RUN_SUCCESS == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.WORKFLOW_ARTIFACT_NAME }}
        path: /results

    - name: Setup Rclone
      if: ${{ inputs.s3_upload == 'true' && env.RUN_SUCCESS == 'true' }}
      uses: AnimMouse/setup-rclone@e4c62ff5f942e489edceaffb563832d970253322
      with:
        rclone_config: ${{ inputs.rclone_config }}
        rclone_version: ${{ inputs.rclone_version }}

    - name: Upload results to S3
      if: ${{ inputs.s3_upload == 'true' && env.RUN_SUCCESS == 'true' }}
      shell: bash
      run: |
        rclone copy --no-traverse /results s3:${{ inputs.s3_bucket }}/${{ inputs.s3_path }}
