name: Hive Tests
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - init

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/hive
        with:
          client: go-ethereum
          simulator: ethereum/sync
