name: Test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ethpandaops/hive-github-action@init
        with:
          client: go-ethereum
          simulator: ethereum/sync
